---
- hosts: all
  become: yes
  tasks:
    - name: create the 'ubuntu' user
      user: name=ubuntu append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'ubuntu' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'ubuntu ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: 
        user: ubuntu 
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - ~/.ssh/*.pub

    - name: disable swap
      command: swapoff -a
      changed_when: true
      when: ansible_swaptotal_mb > 0

    - name: remove swap from fstab
      lineinfile:
        path: '/etc/fstab'
        regexp: '\sswap\s'
        state: 'absent'